# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc_gen import inferencia_pb2 as inferencia__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inferencia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServicoInferenciaStub:
    """Contrato do serviço de inferência distribuído.
    Deve produzir exatamente o mesmo resultado que a interface REST
    para a mesma entrada, como exige o edital.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarInferencia = channel.unary_unary(
                '/inferencia.ServicoInferencia/CriarInferencia',
                request_serializer=inferencia__pb2.PedidoInferencia.SerializeToString,
                response_deserializer=inferencia__pb2.RespostaJobCriado.FromString,
                _registered_method=True)
        self.ConsultarInferencia = channel.unary_unary(
                '/inferencia.ServicoInferencia/ConsultarInferencia',
                request_serializer=inferencia__pb2.PedidoConsulta.SerializeToString,
                response_deserializer=inferencia__pb2.RespostaConsulta.FromString,
                _registered_method=True)


class ServicoInferenciaServicer:
    """Contrato do serviço de inferência distribuído.
    Deve produzir exatamente o mesmo resultado que a interface REST
    para a mesma entrada, como exige o edital.
    """

    def CriarInferencia(self, request, context):
        """Enfileira um texto para inferência e devolve o identificador do job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarInferencia(self, request, context):
        """Consulta o status/resultado de um job pelo identificador.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoInferenciaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarInferencia': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarInferencia,
                    request_deserializer=inferencia__pb2.PedidoInferencia.FromString,
                    response_serializer=inferencia__pb2.RespostaJobCriado.SerializeToString,
            ),
            'ConsultarInferencia': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarInferencia,
                    request_deserializer=inferencia__pb2.PedidoConsulta.FromString,
                    response_serializer=inferencia__pb2.RespostaConsulta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inferencia.ServicoInferencia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inferencia.ServicoInferencia', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServicoInferencia:
    """Contrato do serviço de inferência distribuído.
    Deve produzir exatamente o mesmo resultado que a interface REST
    para a mesma entrada, como exige o edital.
    """

    @staticmethod
    def CriarInferencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inferencia.ServicoInferencia/CriarInferencia',
            inferencia__pb2.PedidoInferencia.SerializeToString,
            inferencia__pb2.RespostaJobCriado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarInferencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inferencia.ServicoInferencia/ConsultarInferencia',
            inferencia__pb2.PedidoConsulta.SerializeToString,
            inferencia__pb2.RespostaConsulta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
