# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inferencia.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inferencia.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inferencia.proto\x12\ninferencia\"!\n\x10PedidoInferencia\x12\r\n\x05texto\x18\x01 \x01(\t\"#\n\x11RespostaJobCriado\x12\x0e\n\x06job_id\x18\x01 \x01(\t\" \n\x0ePedidoConsulta\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"f\n\x10RespostaConsulta\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05texto\x18\x02 \x01(\t\x12\x12\n\nsentimento\x18\x03 \x01(\t\x12\x11\n\tconfianca\x18\x04 \x01(\x01\x12\x0c\n\x04\x65rro\x18\x05 \x01(\t2\xb4\x01\n\x11ServicoInferencia\x12N\n\x0f\x43riarInferencia\x12\x1c.inferencia.PedidoInferencia\x1a\x1d.inferencia.RespostaJobCriado\x12O\n\x13\x43onsultarInferencia\x12\x1a.inferencia.PedidoConsulta\x1a\x1c.inferencia.RespostaConsultab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inferencia_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEDIDOINFERENCIA']._serialized_start=32
  _globals['_PEDIDOINFERENCIA']._serialized_end=65
  _globals['_RESPOSTAJOBCRIADO']._serialized_start=67
  _globals['_RESPOSTAJOBCRIADO']._serialized_end=102
  _globals['_PEDIDOCONSULTA']._serialized_start=104
  _globals['_PEDIDOCONSULTA']._serialized_end=136
  _globals['_RESPOSTACONSULTA']._serialized_start=138
  _globals['_RESPOSTACONSULTA']._serialized_end=240
  _globals['_SERVICOINFERENCIA']._serialized_start=243
  _globals['_SERVICOINFERENCIA']._serialized_end=423
# @@protoc_insertion_point(module_scope)
